type Test {
  _id: String
  total: Int
  createdDate: String
}

type Operations {
  _id: String
  testID: String
  value: Int
  createdDate: String
}

type Query {
  getOperations(_id: String): Int
  getTotal(_id: String): Int
}

type Mutation {
  writeOperation(value: Int): Operations
  addTest: String
  deletTest(_id: String): Boolean
}
