enum Role {
  admin
  director
  manager
}
type User {
  _id: ID  
  avatar: String
  username: String! 
  email: String
  password: String! 
  roles:[Role] 
  createdDate: String

}
input inputUser {
  avatar: String
  username: String
  email: String
}
type Token {
  token: String!
}

type Query {
  getCurrentUser: User
  getUsers: [User]
}

type Mutation {  
  modifyUser(input: inputUser!):User
  deleteUser(id: ID!):User
  signIn(username: String!, password: String!): Token
  signUp(username: String!,email: String!, password: String!): User  
}
